[build]
  command = "npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg", "@google-cloud/vision"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
