-- C1 — full current-price capture: add company/grade/type, widen the unique key.
-- DDL shape generated by `prisma migrate diff --from-url <LOCAL>
--   --to-schema-datamodel prisma/schema.prisma --script`; the IF NOT EXISTS
--   guards are hand-added for idempotency (population_report template). The
--   index name is Prisma's own (truncated) output verbatim, so a later remote
--   `prisma migrate` sees no drift.
-- ADDITIVE-SAFE: existing rows default to (company NULL, grade NULL, type 'raw');
--   each was already unique on the first 5 columns, so the widened index cannot
--   collide. ZERO credits, LOCAL-only this phase.
ALTER TABLE "current_price" ADD COLUMN IF NOT EXISTS "company" TEXT;
ALTER TABLE "current_price" ADD COLUMN IF NOT EXISTS "grade"   TEXT;
ALTER TABLE "current_price" ADD COLUMN IF NOT EXISTS "type"    TEXT NOT NULL DEFAULT 'raw';

DROP INDEX IF EXISTS "current_price_cardId_source_currency_variant_condition_key";

CREATE UNIQUE INDEX IF NOT EXISTS
  "current_price_cardId_source_currency_variant_condition_comp_key"
  ON "current_price" ("cardId", "source", "currency", "variant", "condition", "company", "grade", "type");
