-- Phase 1 Part 1 — PSA population store (PopulationReport).
-- DDL generated by `prisma migrate diff --from-migrations prisma/migrations
--   --to-schema-datamodel prisma/schema.prisma --script`; the IF NOT EXISTS /
--   DO $$ guards are hand-added for idempotency (collection_buckets template).
--   Index/constraint names are Prisma's own output (verified), so a later
--   remote `prisma migrate` sees no drift.
-- PURELY ADDITIVE: a new table + its indexes + FK. No existing row is touched,
--   no backfill, no dedupe. ZERO credits, LOCAL-only this phase.
CREATE TABLE IF NOT EXISTS "population_report" (
  "id"          TEXT NOT NULL,
  "cardId"      TEXT NOT NULL,
  "source"      TEXT NOT NULL DEFAULT 'scrydex',
  "company"     TEXT NOT NULL DEFAULT 'PSA',
  "language"    TEXT NOT NULL DEFAULT 'English',
  "grades"      JSONB NOT NULL,
  "total"       INTEGER NOT NULL,
  "refreshedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL,
  CONSTRAINT "population_report_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "population_report_cardId_source_company_language_key"
  ON "population_report" ("cardId", "source", "company", "language");

CREATE INDEX IF NOT EXISTS "population_report_cardId_idx"
  ON "population_report" ("cardId");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'population_report_cardId_fkey'
  ) THEN
    ALTER TABLE "population_report"
      ADD CONSTRAINT "population_report_cardId_fkey"
      FOREIGN KEY ("cardId") REFERENCES "card"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;
