-- Per-grade price history capture: add company/grade/type, widen the unique key.
-- DDL shape generated by `prisma migrate diff --from-url <LOCAL>
--   --to-schema-datamodel prisma/schema.prisma --script`; the IF NOT EXISTS
--   guards are hand-added for idempotency (current_price template). The DROP /
--   CREATE index name is Prisma's own (truncated) output verbatim — both the
--   old 6-column key and the new 9-column key truncate to the SAME 63-char
--   identifier, so this drops and recreates one name. A later remote
--   `prisma migrate` therefore sees no drift.
-- ADDITIVE-SAFE: existing rows default to (company NULL, grade NULL, type 'raw');
--   each was already unique on the first 6 columns, so the widened index cannot
--   collide. ZERO credits, LOCAL-only this phase.
ALTER TABLE "pricing_history" ADD COLUMN IF NOT EXISTS "company" TEXT;
ALTER TABLE "pricing_history" ADD COLUMN IF NOT EXISTS "grade"   TEXT;
ALTER TABLE "pricing_history" ADD COLUMN IF NOT EXISTS "type"    TEXT NOT NULL DEFAULT 'raw';

DROP INDEX IF EXISTS "pricing_history_cardId_recordedAt_source_currency_variant_c_key";

CREATE UNIQUE INDEX IF NOT EXISTS
  "pricing_history_cardId_recordedAt_source_currency_variant_c_key"
  ON "pricing_history" ("cardId", "recordedAt", "source", "currency", "variant", "condition", "company", "grade", "type");
